# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'cityImage'
copyright = '2024, Gabriele Filomena'
author = 'Gabriele Filomena'
release = '1.21'
html_title = ""

import os
import sys
sys.path.insert(0, os.path.abspath('../cityImage'))

import cityImage

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = [
    'nbsphinx',  # Adds support for Jupyter Notebooks (.ipynb files) in the documentation.
    'sphinx.ext.mathjax',  # Allows for rendering of mathematical notation using MathJax.
    'sphinx.ext.viewcode',  # Includes links to highlighted source code in the documentation.
    'myst_parser',  # Replaces recommonmark for Markdown support
    'sphinx.ext.autodoc',  # Automatically generates documentation from docstrings in the code.
    'sphinx.ext.napoleon',  # Supports Google style and NumPy style docstrings for easier writing of documentation.
    'sphinx_autodoc_typehints',  # Adds type hints to the function signatures in the generated documentation.
    'sphinx.ext.autosummary',  # Generates summary listings of modules, classes, functions, etc., and creates stub pages for them.
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'pydata_sphinx_theme'

html_theme_options = {
    "github_url": "https://github.com/cityImage",
    "twitter_url": "https://twitter.com/gfilo",
    "logo": {
        "image_light": "logo.png",
        "image_dark": "logo.png",
    },
}

html_static_path = ["_static"]

html_theme_options.update({
    'navigation_depth': 4,
    'show_prev_next': True,
    'show_toc_level': 2,
    'page_sidebar_items': ['page-toc', 'edit-this-page', 'page-nav'],  # Adjust as needed
})



# -- Extension configuration -------------------------------------------------

# Generate the API documentation when building
autosummary_generate = True  # Automatically generate summary pages and stub pages for items listed in autosummary directives.
autosummary_imported_members = True  # Include members imported from other modules in the generated documentation.
numpydoc_show_class_members = True  # Include class members (methods and attributes) in the generated documentation.
class_members_toctree = True
numpydoc_show_inherited_class_members = True  # Include inherited class members in the generated documentation.
numpydoc_class_members_toctree = True  # Create a separate toctree (table of contents tree) for class members.
numpydoc_use_plots = True  # Enable the generation of plots for examples in NumPy-style docstrings.
autodoc_typehints = "none"  # Disable the inclusion of type hints in the function signatures generated by autodoc.
