name: cityImage
channels:
  - defaults
dependencies:
  - python=3.10.9
  - geopandas=0.12.2
  - matplotlib=3.6.3
  - numpy=1.24.1
  - networkx=3.0
  - pandas=1.5.3
  - pyproj=3.4.1
  - shapely=2.0.0
  - tqdm=4.65.0
  - fiona=1.8.22
  - pip
  - pip:
      - cityImage 
      - attrs==22.2.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - mapclassify==2.5.0
      - osmnx==1.9.1
      - python-louvain==0.16
      - pyvista==0.43.2
      - igraph==0.11.6
